#端口号
server:
  port: 8080

#mysql数据库
spring:
  thymeleaf:
    cache: false
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #连接池springboot自带
    hikari:
      #连接池名字
      pool-name: DateHilariCP
      #最小空闲连接
      minimum-idle: 5
      #空闲连接存活最大时间默认10分钟（600000）
      idle-timeout: 180000
      #最大连接数 默认10
      maximum-pool-size: 10
      #从连接池返回自动提交
      auto-commit: true
      #连接最大存活时间 0表示永久 1800000  30分钟
      max-lifetime: 1800000
      #连接超时时间默认 30000  30秒
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  ## 启⽤热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


  ## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxxx.supermarket.vo;com.xxxx.supermarket.query;com.xxxx.supermarket.dto
  configuration:
    map-underscore-to-camel-case: true
  ## pageHelper 分⻚
pagehelper:
  helper-dialect: mysql

#日志
logging:
  level:
    com:
      xxxx:
        crm:
          dao: debug