#端口号
server:
  port: 8080
  servlet:
    context-path: /shop

#mysql数据库
spring:
  thymeleaf:
    cache: false
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  ## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
  ## 启⽤热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


  ## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxxx.supermarket.vo;com.xxxx.supermarket.query;com.xxxx.supermarket.dto
  configuration:
    map-underscore-to-camel-case: true
  ## pageHelper 分⻚
pagehelper:
  helper-dialect: mysql

#日志
logging:
  level:
    com:
      xxxx:
        supermarket:
          dao: debug